{"uuid": "e757d6a9-1b87-45a6-8627-ba54148e85d7", "children": ["ad56a03a-55b0-45f7-a405-52041a71848f"], "befores": [{"name": "load_config", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'C:\\\\Users\\\\dhamyan\\\\PycharmProjects\\\\PythonProject\\\\PythonProject\\\\qa-automation-api\\\\test\\\\data\\\\endpoints_config.json'\n", "trace": "  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\pluggy\\_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1196, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\dhamyan\\AppData\\Local\\Programs\\Python\\Python313\\Lib\\site-packages\\_pytest\\fixtures.py\", line 930, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\dhamyan\\PycharmProjects\\PythonProject\\PythonProject\\qa-automation-api\\test\\conftest.py\", line 12, in load_config\n    with open(config_path, \"r\") as f:\n         ~~~~^^^^^^^^^^^^^^^^^^\n"}, "start": 1759428299772, "stop": 1759428299772}], "start": 1759428299772, "stop": 1759428299990}